# -*- coding: utf-8 -*-
"""Web_scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVoMTVtX8PgocUlQMmvHPucbWyLaT5Ur
"""

pip install requests

pip install bs4

import requests
from bs4 import BeautifulSoup as bs
import csv

res = requests.get("https://codedamn-classrooms.github.io/webscraper-python-codedamn-classroom-website/")

print(res.status_code)

soup = bs(res.content, 'html.parser')

title = soup.title.text
body = soup.body
head = soup.head

print("Title: ", title)
print("Head: ", head)
print("Body: ", body)

#scraping top products and respective review pairs
products = soup.select('div.thumbnail')

top_items = list()
for element in products:
  name = element.select("a.title")[0].text.strip()
  rating = element.select("div.ratings")[0].text.strip()

  info = {
      "title" : name,
      "review" : rating
  }
  top_items.append(info)
print(top_items)

#scraping link and text attribute pairs
pairs = []
trials = soup.select("a")
for trial in trials:
  text = trial.text
  text = text.strip() if text is not None else ''
  link = trial.get('href') # .get goes within <> for attributes and returns their value
  link = link.strip() if link is not None else ''

  dict = {
      "href" : link,
      "text" : text
  }
  pairs.append(dict)
pairs

products = soup.select('div.thumbnail')

all_products = list()

for product in products:
  name = product.select("a")[0].text.strip() #Selects the product name from within the <a></a> tag by removing all tags
  #product.select("h4")[1].text.strip() gives same result. Follow the intuition of .select("tag")
  
  price = product.select("h4")[0].text.strip() #Selects the first(0) h4 tag, which encloses the item price, from the list. then removes the html tags
  
  desc_ = product.select("p")[0].text.strip().split(",")
  desc_ = [string.replace(string, string.strip()) for string in desc_] # To remove whitespaces around individual words and return the updated list. 
                                                                        # have to figure out how to remove those within words(maybe regex).
  
  reviews = product.select("p")[1].text.strip()
  #Alt  product.select("div")[1].text.strip() for future studying lol

  image = product.select("img")[0].get("src")

  product_info = {
      "Name": name,
      "Price": price,
      "Description": desc_,
      "Reviews": reviews,
      "Image": image
  }

  all_products.append(product_info)

keys = all_products[0].keys() #Get the keys from one of the dictionaries

with open('products.csv', 'w', newline='') as output_file:
    dict_writer = csv.DictWriter(output_file, keys)
    dict_writer.writeheader()
    dict_writer.writerows(all_products)

